name: ci-cd 

run-name: BuildDotnet

on: 
    workflow_dispatch:
        inputs:
            environments:
                description: To deploy for env
                type: environment
                required: true
            deploy:
                description: deploy 
                type: boolean

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: code checkout
              uses: actions/checkout@v4

            - name: setup dotnet
              uses: actions/setup-dotnet@v4
              with:
                 dotnet-version: '6.0.x'

            
            - name: Dotnet Build
              run: |
                dotnet build
          

           